sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yuwei6813.
  alioss:
    endpoint: oss-cn-chengdu.aliyuncs.com
    access-key-id: LTAI5t7NSpFqgdeUZ9SeEMwg
    access-key-secret: XyZBaCsc6D3IipY3OwXvMFDytbYaf8
    bucket-name: sky-take-out-akuya48
  redis:
    host: localhost
    port: 6379
    database: 10 # 默认有0-15共16个数据库，设定使用Redis的指定数据库